org: tienpham212
app: aws-trello
service: boardAPI
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  environment:
   DYNAMODB_TABLE: ${self:service}-BoardMain-${sls:stage}
  iam:
    role:
      statements:
        - Effect: 'Allow'
          Action:
            - 'dynamodb:PutItem'
            - 'dynamodb:Get*'
            - 'dynamodb:Scan*'
            - 'dynamodb:UpdateItem'
            - 'dynamodb:DeleteItem'
          Resource: arn:aws:dynamodb:${aws:region}:${aws:accountId}:table/${self:service}-BoardMain-${sls:stage}

functions:     	
  createBoard:
    handler: src/handlers/boardHandler.createBoard
    events:
      - httpApi:
          path: /create
          method: post
  getBoards:
    handler: src/handlers/boardHandler.getBoards
    events:
      - httpApi:
          path: /get
          method: get
  getBoardItem:
    handler: src/handlers/boardHandler.getBoardItem
    events:
      - httpApi:
          path: /get/{id}
          method: get
  deleteBoardItem:
    handler: src/handlers/boardHandler.deleteBoardItem
    events:
      - httpApi:
          path: /delete
          method: post
  updateBoardItem:
    handler: src/handlers/boardHandler.updateBoardItem
    events:
      - httpApi:
          path: /update
          method: post
resources:
  Resources:
    CustomerTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: primary_key
            AttributeType: S
          - AttributeName: columnOrder
            AttributeType: S
        BillingMode: PAY_PER_REQUEST
        KeySchema:
          - AttributeName: primary_key
            KeyType: HASH
        TableName: ${self:service}-BoardMain-${sls:stage}
	
plugins:
  - serverless-offline

	
custom:
  serverless-offline:
    httpPort: 3005
